### PR TITLE
Add 步骤13-步骤13-Prometheus&Grafana监控.md

### PR DESCRIPTION
**Pull request by toreydai**
*Description of changes:
Add 步骤13-步骤13-Prometheus&Grafana监控.md

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by toreydai — COMMENTED** [review]
Add 清理环境

**Comment by stevensu1977** [comment]
I add comments for your PR,

1. add requirement describe , complete step 9, add helm stable repo

2. In China  we have some security reason, so I strong suggestion use ClusterIP for prometheus-service and access it through kubectl proxy.

cat << EOF > ./prometheus-service.yml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    chart: prometheus-11.0.4
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-nginx
  namespace: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: prometheus
  type: ClusterIP
EOF


kubectl apply -f prometheus-service.yml

kubectl proxy --port=8080 --address='0.0.0.0' --disable-filter=true

open brower, http://localhost:8080/api/v1/namespaces/prometheus/services/prometheus-nginx/proxy/graph

**Review by toreydai — COMMENTED** [review]
Modify Prometheus Service

**Comment by stevensu1977** [comment]
Thank your PR !

**Pull request merged**
